### ISSUE TITLE
Required API changes

### ISSUE THREAD

**Issue by bizzare-owl** [YummyPotatoPie/SymbolStreams#2]
# Must changes some methods implementation and add some methods

## Requires implementation change
- LoadedStream.Peek()
- LoadedStream.Next()
- LoadedStream.EndOfStream()

## Requires to add
- LoadedStream.Reset() - sets Position to begin of the stream

**Comment by YummyPotatoPie** [comment]
LoadedStream.Reset() must be renamed because there are conflict with IterativeLoadedStream.Reset()

**Comment by bizzare-owl** [comment]
Complete
